#!/usr/bin/env bash
# ============================================================================
# Dream Server — Vast.ai Networking & Access Layer
# ============================================================================
# Part of: p2p-gpu/lib/
# Purpose: Port exposure, Caddy reverse proxy, health page, Cloudflare
#          tunnel, SSH tunnel script, access info display
#
# Expects: LOGFILE, SCRIPT_NAME, log(), warn(), err(), env_set(), env_get(),
#          discover_all_services(), discover_service_ports()
# Provides: expose_ports_for_vastai(), setup_reverse_proxy(),
#           generate_health_page(), setup_cloudflare_tunnel(),
#           generate_ssh_tunnel_script(), print_access_info()
#
# Modder notes:
#   Caddy failure is non-fatal — falls back to SSH tunnel mode.
#   print_access_info is split into sub-functions for maintainability.
#
# SPDX-License-Identifier: Apache-2.0
# ============================================================================

set -euo pipefail

# Rewrite 127.0.0.1 → 0.0.0.0 in compose port bindings for Vast.ai access
expose_ports_for_vastai() {
  local ds_dir="$1"
  log "Rebinding Docker ports from 127.0.0.1 → 0.0.0.0 for Vast.ai external access"
  local count=0
  while IFS= read -r -d '' compose_file; do
    if grep -q '"127\.0\.0\.1:' "$compose_file"; then
      sed -i 's/"127\.0\.0\.1:/"0.0.0.0:/g' "$compose_file"
      count=$((count + 1))
    fi
  done < <(find "$ds_dir" -maxdepth 4 \
    \( -name "docker-compose*.yml" -o -name "compose*.yaml" -o -name "compose*.yml" \) \
    -print0 2>&1 || warn "find compose files failed (non-fatal)")
  log "Rebound ports in ${count} compose file(s) to 0.0.0.0"
}

# Deploy Caddy reverse proxy for single-port access
setup_reverse_proxy() {
  local ds_dir="$1"
  local proxy_port="${2:-8080}"
  local env_file="${ds_dir}/.env"

  _install_caddy || return 1
  _generate_caddyfile "$ds_dir" "$proxy_port" "$env_file"
  _start_caddy "$ds_dir" "$proxy_port" "$env_file"
}

_install_caddy() {
  command -v caddy &>/dev/null && return 0
  log "Installing Caddy reverse proxy..."
  if apt-get install -y -qq debian-keyring debian-archive-keyring apt-transport-https 2>>"$LOGFILE" \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
       | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg 2>>"$LOGFILE" \
    && curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
       | tee /etc/apt/sources.list.d/caddy-stable.list > /dev/null \
    && apt-get update -qq 2>>"$LOGFILE" \
    && apt-get install -y -qq caddy 2>>"$LOGFILE"; then
    log "Caddy installed successfully"
  else
    warn "Caddy install failed — falling back to SSH tunnel mode"
    return 1
  fi
}

_generate_caddyfile() {
  local ds_dir="$1" proxy_port="$2" env_file="$3"
  local caddy_dir="${ds_dir}/config/caddy"
  mkdir -p "$caddy_dir"

  local webui_port
  webui_port="$(env_get "$env_file" "WEBUI_PORT")"
  webui_port="${webui_port:-3000}"

  # Dashboard is the main DreamServer panel — it owns the root route.
  # Its nginx serves SPA assets and proxies /api/ → dashboard-api with auth.
  local dashboard_port
  dashboard_port="$(env_get "$env_file" "DASHBOARD_PORT")"
  dashboard_port="${dashboard_port:-3001}"

  cat > "${caddy_dir}/Caddyfile" << CADDYEOF
# DreamServer reverse proxy — auto-generated by vastai setup
{
  auto_https off
  admin off
}

:${proxy_port} {
  # Dashboard — main DreamServer panel (root route)
  handle / {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }
  handle /api/* {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }
  handle /assets/* {
    reverse_proxy 127.0.0.1:${dashboard_port}
  }

  # Open WebUI — full access via SSH tunnel (port ${webui_port})
  handle_path /chat/* {
    reverse_proxy 127.0.0.1:${webui_port}
  }

  handle_path /health {
    root * ${caddy_dir}
    file_server
    try_files /health.html
  }

CADDYEOF

  # Append auto-discovered service routes (skip root-handled services)
  while IFS='|' read -r sid port_env port_def _name _cat proxy_mode _startup _cname; do
    [[ -z "$port_env" || "$sid" == "open-webui" || "$sid" == "dashboard" ]] && continue
    local svc_port
    svc_port="$(env_get "$env_file" "$port_env")"
    svc_port="${svc_port:-$port_def}"
    [[ -z "$svc_port" ]] && continue

    if [[ "$proxy_mode" == "root" ]]; then
      printf '  handle /%s/* {\n    reverse_proxy 127.0.0.1:%s\n  }\n\n' \
        "$sid" "$svc_port" >> "${caddy_dir}/Caddyfile"
    else
      printf '  handle_path /%s/* {\n    reverse_proxy 127.0.0.1:%s\n  }\n\n' \
        "$sid" "$svc_port" >> "${caddy_dir}/Caddyfile"
    fi
  done < <(discover_all_services "$ds_dir")

  # Ollama (base service, no manifest)
  local ollama_port
  ollama_port="$(env_get "$env_file" "OLLAMA_PORT")"
  ollama_port="${ollama_port:-8080}"
  cat >> "${caddy_dir}/Caddyfile" << CADDYTAIL
  handle_path /ollama/* {
    reverse_proxy 127.0.0.1:${ollama_port}
  }
  handle_path /v1/* {
    reverse_proxy 127.0.0.1:${ollama_port}
  }
}
CADDYTAIL

  generate_health_page "${caddy_dir}/health.html" "$ds_dir"
}

_start_caddy() {
  local ds_dir="$1" proxy_port="$2" env_file="$3"
  local caddy_dir="${ds_dir}/config/caddy"

  if pgrep -x caddy > /dev/null 2>&1; then
    local old_pid
    old_pid=$(pgrep -x caddy | head -1)
    kill "$old_pid" || warn "could not kill old caddy PID ${old_pid} (non-fatal)"
    sleep 1
  fi

  mkdir -p "${ds_dir}/logs"
  nohup caddy run --config "${caddy_dir}/Caddyfile" --adapter caddyfile \
    >> "${ds_dir}/logs/caddy-proxy.log" 2>&1 &
  local caddy_pid=$!
  sleep 2

  if kill -0 "$caddy_pid" 2>&1; then
    log "Caddy reverse proxy running on port ${proxy_port} (PID: ${caddy_pid})"
    env_set "${env_file}" "REVERSE_PROXY_PORT" "$proxy_port"
    return 0
  else
    warn "Caddy failed to start — check ${ds_dir}/logs/caddy-proxy.log"
    return 1
  fi
}

# Generate health dashboard HTML page
generate_health_page() {
  local output_file="$1"
  cat > "$output_file" << 'HEALTHEOF'
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>DreamServer — Health</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif;
           background: #0f1117; color: #e0e0e0; padding: 2rem; }
    h1 { color: #7dd3fc; margin-bottom: 1.5rem; font-size: 1.5rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(240px, 1fr)); gap: 1rem; }
    .card { background: #1a1d27; border-radius: 12px; padding: 1rem; border: 1px solid #2a2d37; }
    .card h3 { font-size: 0.95rem; margin-bottom: 0.5rem; }
    .status { display: inline-block; width: 10px; height: 10px; border-radius: 50%; margin-right: 8px; }
    .healthy { background: #22c55e; } .running { background: #eab308; }
    .stopped { background: #6b7280; } .error   { background: #ef4444; }
    .port { color: #7dd3fc; font-size: 0.85rem; }
    .ts { color: #6b7280; font-size: 0.8rem; margin-top: 1rem; }
  </style>
</head>
<body>
  <h1>DreamServer Health</h1>
  <div class="grid" id="services"><div class="card"><p>Loading...</p></div></div>
  <p class="ts">Auto-refreshes every 15s</p>
  <script>
    async function refresh() {
      try {
        const r = await fetch('/dashboard-api/api/v1/status');
        const data = await r.json();
        const grid = document.getElementById('services');
        grid.innerHTML = '';
        (data.services || []).forEach(s => {
          const cls = s.healthy ? 'healthy' : (s.status === 'running' ? 'running' : 'stopped');
          grid.innerHTML += '<div class="card"><h3><span class="status '+cls+'"></span>'+s.name+'</h3><span class="port">:'+( s.port||'—')+'</span></div>';
        });
      } catch(e) {
        document.getElementById('services').innerHTML =
          '<div class="card"><p>Dashboard API not available.</p></div>';
      }
    }
    refresh(); setInterval(refresh, 15000);
  </script>
</body>
</html>
HEALTHEOF
  log "Generated health dashboard at ${output_file}"
}

# Start Cloudflare Tunnel if token is configured
setup_cloudflare_tunnel() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local cf_token
  cf_token="$(env_get "$env_file" "CLOUDFLARE_TUNNEL_TOKEN")"
  [[ -z "$cf_token" ]] && return 0

  log "Cloudflare Tunnel token detected — setting up tunnel"
  if ! command -v cloudflared &>/dev/null; then
    local cf_tmp="/tmp/cloudflared-$$"
    local cf_checksum_url="https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.sha256"
    curl -sL https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 \
      -o "$cf_tmp" || { warn "cloudflared download failed (non-fatal)"; rm -f "$cf_tmp"; return 0; }
    # Verify checksum when available
    local expected_sha
    expected_sha=$(curl -sL --max-time 10 "$cf_checksum_url" 2>/dev/null | awk '{print $1}' || echo "")
    if [[ -n "$expected_sha" ]]; then
      local actual_sha
      actual_sha=$(sha256sum "$cf_tmp" | awk '{print $1}')
      if [[ "$actual_sha" != "$expected_sha" ]]; then
        err "cloudflared checksum mismatch (expected: ${expected_sha:0:12}…, got: ${actual_sha:0:12}…)"
        rm -f "$cf_tmp"
        warn "Skipping Cloudflare tunnel — binary integrity check failed"
        return 0
      fi
      log "cloudflared checksum verified"
    else
      warn "cloudflared checksum not available — skipping integrity check"
    fi
    mv "$cf_tmp" /usr/local/bin/cloudflared
    chmod +x /usr/local/bin/cloudflared
  fi

  local proxy_port
  proxy_port="$(env_get "$env_file" "REVERSE_PROXY_PORT")"
  proxy_port="${proxy_port:-3000}"

  mkdir -p "${ds_dir}/logs"
  # [FIX: cf-token] Pass token via env var, not CLI arg (hidden from ps aux)
  TUNNEL_TOKEN="$cf_token" nohup cloudflared tunnel --no-autoupdate run --token-from-env TUNNEL_TOKEN \
    >> "${ds_dir}/logs/cloudflared.log" 2>&1 &
  local cf_pid=$!
  _store_pid "cloudflared" "$cf_pid" 2>/dev/null || true
  log "Cloudflare Tunnel started (PID: ${cf_pid}) — HTTPS access active"
}

# Generate auto-reconnecting SSH tunnel script
generate_ssh_tunnel_script() {
  local ds_dir="$1"
  local host_ip ssh_port
  host_ip="${PUBLIC_IPADDR:-$(curl -sf --max-time 5 ifconfig.me || echo '<your-vast-ip>')}"
  ssh_port="${VAST_TCP_PORT_22:-22}"

  local script_path="${ds_dir}/connect-tunnel.sh"
  {
    echo '#!/usr/bin/env bash'
    echo '# DreamServer — auto-reconnecting SSH tunnel (run on YOUR LOCAL machine)'
    echo "HOST=\"${host_ip}\""
    echo "SSH_PORT=\"${ssh_port}\""
    echo 'FORWARDS="'
    discover_service_ports "$ds_dir" | while IFS='|' read -r _key port _label; do
      echo "  -L ${port}:127.0.0.1:${port} \\"
    done
    echo '"'
    echo 'DELAY=5'
    echo 'while true; do'
    echo '  ssh -N -o ServerAliveInterval=15 -o ServerAliveCountMax=3 \'
    echo '      -o ExitOnForwardFailure=yes \'
    echo '      -p "$SSH_PORT" $FORWARDS root@"$HOST"'
    echo '  echo "[!] Connection lost. Reconnecting in ${DELAY}s..."'
    echo '  sleep "$DELAY"'
    echo '  DELAY=$(( DELAY < 60 ? DELAY * 2 : 60 ))'
    echo 'done'
  } > "$script_path"
  chmod +x "$script_path"
  log "Generated auto-reconnecting tunnel script: ${script_path}"
}

# ── Print access info (split into sub-functions) ───────────────────────────
print_access_info() {
  local ds_dir="$1"
  local env_file="${ds_dir}/.env"
  local host_ip ssh_port
  host_ip="${PUBLIC_IPADDR:-$(curl -sf --max-time 5 ifconfig.me || echo '<your-vast-ip>')}"
  ssh_port="${VAST_TCP_PORT_22:-22}"

  echo ""
  echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo -e "${CYAN}${BOLD}  DreamServer is ready on Vast.ai!${NC}"
  echo -e "${CYAN}${BOLD}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}"
  echo ""
  echo -e "${BOLD}Working directory:${NC} ${ds_dir}"
  echo -e "${BOLD}Setup log:${NC}         ${LOGFILE}"
  echo ""

  _print_proxy_section "$ds_dir" "$env_file" "$host_ip"
  _print_ssh_section "$ds_dir" "$env_file" "$host_ip" "$ssh_port"
  _print_service_list "$ds_dir"
  _print_model_upload_help "$ds_dir" "$host_ip" "$ssh_port"
  _print_commands_help "$ds_dir"
}

_print_proxy_section() {
  local ds_dir="$1" env_file="$2" host_ip="$3"
  local proxy_port
  proxy_port="$(env_get "$env_file" "REVERSE_PROXY_PORT")"
  if [[ -n "$proxy_port" ]] && pgrep -x caddy > /dev/null 2>&1; then
    echo -e "${GREEN}${BOLD}▸ Reverse Proxy Active (single-port access!)${NC}"
    echo ""
    echo -e "  Dashboard:    ${BOLD}http://${host_ip}:${proxy_port}/${NC}"
    echo "    Open WebUI:     http://${host_ip}:${proxy_port}/chat/"
    echo "    n8n Workflows:  http://${host_ip}:${proxy_port}/n8n/"
    echo "    Health Status:  http://${host_ip}:${proxy_port}/health"
    echo ""
  fi
}

_print_ssh_section() {
  local ds_dir="$1" env_file="$2" host_ip="$3" ssh_port="$4"
  echo -e "${BOLD}━━━ SSH Tunnel (recommended for Vast.ai) ━━━${NC}"
  echo ""

  local tunnel_flags=""
  while IFS='|' read -r _key port _label; do
    tunnel_flags="${tunnel_flags} -L ${port}:127.0.0.1:${port}"
  done < <(discover_service_ports "$ds_dir")

  echo -e "  ${BOLD}Linux / macOS:${NC}"
  echo -e "${DIM}ssh -p ${ssh_port} -i ~/.ssh/id_ed25519${tunnel_flags} root@${host_ip}${NC}"
  echo ""
  echo -e "  ${BOLD}Windows PowerShell (one line):${NC}"
  echo -e "${DIM}ssh -p ${ssh_port} -i \$env:USERPROFILE\\.ssh\\id_ed25519${tunnel_flags} root@${host_ip}${NC}"
  echo ""

  if [[ -f "${ds_dir}/connect-tunnel.sh" ]]; then
    echo -e "  ${BOLD}Auto-reconnect:${NC} scp -P ${ssh_port} root@${host_ip}:${ds_dir}/connect-tunnel.sh . && bash connect-tunnel.sh"
    echo ""
  fi
}

_print_service_list() {
  local ds_dir="$1"
  echo -e "${BOLD}Services:${NC}"
  discover_service_ports "$ds_dir" | while IFS='|' read -r _key port label; do
    printf "  %-22s http://localhost:%s\n" "${label}:" "${port}"
  done
  echo ""
}

_print_model_upload_help() {
  local ds_dir="$1" host_ip="$2" ssh_port="$3"
  echo -e "${BOLD}Upload Custom Models:${NC}"
  echo "  scp -P ${ssh_port} my-model.gguf root@${host_ip}:${ds_dir}/data/models/"
  echo "  # Then: edit .env GGUF_FILE=my-model.gguf && docker restart dream-llama-server"
  echo ""
}

_print_commands_help() {
  local ds_dir="$1"
  echo -e "${BOLD}Commands:${NC}"
  echo "  bash ${SCRIPT_NAME} --status     # Check health"
  echo "  bash ${SCRIPT_NAME} --info       # Connection details"
  echo "  bash ${SCRIPT_NAME} --fix        # Apply fixes + restart"
  echo "  bash ${SCRIPT_NAME} --resume     # Quick restart after SSH drop"
  echo "  bash ${SCRIPT_NAME} --teardown   # Stop all (save billing)"
  echo ""
}
