#!/usr/bin/env bash
# ap-mode.sh — bring up / tear down Dream Server's first-boot AP.
#
# Mode of operation:
#   up      Bring up the AP (configure interface, start hostapd + dnsmasq,
#           install iptables rules). DESTRUCTIVE: takes the configured
#           wireless interface off NetworkManager.
#   down    Stop hostapd + dnsmasq, remove iptables rules, hand the
#           interface back to NetworkManager. Idempotent.
#   status  Print a JSON status snapshot. Read-only, safe to run.
#
# OPT-IN ONLY. The systemd unit shipped alongside this script is
# disabled by default. The first-boot wizard in PR-11 will toggle it
# when DREAM_AP_MODE=true is set in .env AND the device isn't yet
# configured. Until then, every invocation has to be explicit.
#
# This script is Linux-only and assumes:
#   * hostapd, dnsmasq, iptables installed and on $PATH
#   * NetworkManager available (we use nmcli to release / reclaim the iface)
#   * The wireless interface supports AP mode (`iw list | grep -A4 "Supported interface modes" | grep AP`)
#   * Run as root (or under a service unit with the right capabilities)
#
# Config: read from /etc/dream/ap-mode.conf if it exists, otherwise
# falls back to sane defaults documented in docs/AP-MODE.md.

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONF_DIR="${DREAM_AP_CONF_DIR:-/etc/dream}"
RUN_DIR="${DREAM_AP_RUN_DIR:-/run/dream-ap-mode}"
STATE_FILE="${RUN_DIR}/state.json"
HOSTAPD_CONF="${RUN_DIR}/hostapd.conf"
DNSMASQ_CONF="${RUN_DIR}/dnsmasq.conf"
HOSTAPD_PID="${RUN_DIR}/hostapd.pid"
DNSMASQ_PID="${RUN_DIR}/dnsmasq.pid"

# Defaults — override in /etc/dream/ap-mode.conf
DREAM_AP_SSID="${DREAM_AP_SSID:-Dream-Setup}"
DREAM_AP_PASSWORD="${DREAM_AP_PASSWORD:-}"
DREAM_AP_INTERFACE="${DREAM_AP_INTERFACE:-wlan0}"
DREAM_AP_GATEWAY_IP="${DREAM_AP_GATEWAY_IP:-192.168.7.1}"
DREAM_AP_NETMASK="${DREAM_AP_NETMASK:-255.255.255.0}"
DREAM_AP_DHCP_RANGE="${DREAM_AP_DHCP_RANGE:-192.168.7.10,192.168.7.50,1h}"
DREAM_AP_CHANNEL="${DREAM_AP_CHANNEL:-6}"

# Load operator overrides if present. Sourced — be deliberate about what
# you put in there.
if [[ -f "${CONF_DIR}/ap-mode.conf" ]]; then
  # shellcheck disable=SC1091
  source "${CONF_DIR}/ap-mode.conf"
fi

log() { printf '[ap-mode] %s\n' "$*" >&2; }
err() { printf '[ap-mode] ERROR: %s\n' "$*" >&2; }

# --- Preflight ----------------------------------------------------------------

require_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    err "must run as root (currently $(id -un))"
    return 1
  fi
}

require_linux() {
  if [[ "$(uname -s)" != "Linux" ]]; then
    err "AP mode only supported on Linux (this is $(uname -s))"
    return 1
  fi
}

require_binaries() {
  local missing=()
  for bin in hostapd dnsmasq iptables ip nmcli; do
    if ! command -v "$bin" >/dev/null 2>&1; then
      missing+=("$bin")
    fi
  done
  if (( ${#missing[@]} > 0 )); then
    err "missing required binaries: ${missing[*]}"
    err "install with: apt install hostapd dnsmasq iptables network-manager"
    return 1
  fi
}

require_password() {
  # Open APs are tolerated but called out — for first-boot AP we
  # *strongly* recommend setting a per-device password so the unit
  # doesn't accept random clients during the wizard window.
  if [[ -z "${DREAM_AP_PASSWORD}" ]]; then
    log "WARNING: DREAM_AP_PASSWORD unset — bringing up an open AP."
    log "  Set DREAM_AP_PASSWORD in ${CONF_DIR}/ap-mode.conf to require auth."
  elif [[ ${#DREAM_AP_PASSWORD} -lt 8 ]]; then
    err "DREAM_AP_PASSWORD must be at least 8 characters (WPA2 minimum)"
    return 1
  fi
}

interface_supports_ap() {
  # Best-effort check via iw. Not all drivers report capabilities cleanly;
  # we warn rather than fail-hard if iw isn't available.
  if ! command -v iw >/dev/null 2>&1; then
    log "WARNING: 'iw' not available — skipping AP-capability check"
    return 0
  fi
  if ! iw list 2>/dev/null | grep -A20 "Supported interface modes" | grep -q "\* AP"; then
    err "interface does not advertise AP mode in 'iw list' output"
    err "this driver may not support hostapd"
    return 1
  fi
}

# --- Bring up -----------------------------------------------------------------

write_hostapd_conf() {
  cat > "${HOSTAPD_CONF}" <<HEREDOC
# Auto-generated by ap-mode.sh — do not edit by hand.
interface=${DREAM_AP_INTERFACE}
driver=nl80211
ssid=${DREAM_AP_SSID}
hw_mode=g
channel=${DREAM_AP_CHANNEL}
auth_algs=1
wmm_enabled=1
HEREDOC

  if [[ -n "${DREAM_AP_PASSWORD}" ]]; then
    cat >> "${HOSTAPD_CONF}" <<HEREDOC
wpa=2
wpa_key_mgmt=WPA-PSK
wpa_pairwise=CCMP
rsn_pairwise=CCMP
wpa_passphrase=${DREAM_AP_PASSWORD}
HEREDOC
  fi
  chmod 0600 "${HOSTAPD_CONF}"
}

write_dnsmasq_conf() {
  # Listen only on the AP interface. address=/#/<gateway> resolves every
  # hostname to the gateway IP — the classic captive-portal trick, no
  # separate DNS responder needed.
  cat > "${DNSMASQ_CONF}" <<HEREDOC
# Auto-generated by ap-mode.sh — do not edit by hand.
interface=${DREAM_AP_INTERFACE}
bind-interfaces
except-interface=lo
listen-address=${DREAM_AP_GATEWAY_IP}
dhcp-range=${DREAM_AP_DHCP_RANGE}
dhcp-option=3,${DREAM_AP_GATEWAY_IP}
dhcp-option=6,${DREAM_AP_GATEWAY_IP}
# Captive-portal DNS: every name resolves to the device's setup IP.
address=/#/${DREAM_AP_GATEWAY_IP}
# Don't read /etc/resolv.conf upstream — we ARE the resolver.
no-resolv
no-hosts
log-facility=${RUN_DIR}/dnsmasq.log
HEREDOC
  chmod 0600 "${DNSMASQ_CONF}"
}

install_iptables_rules() {
  # Redirect HTTP / HTTPS originating on the AP interface to the gateway.
  # This + the wildcard DNS = captive portal. We tag rules with a Dream
  # comment so teardown can remove only what we added.
  iptables -t nat -A PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 80 \
    -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:80" -m comment --comment "dream-ap-mode"
  iptables -t nat -A PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 443 \
    -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:443" -m comment --comment "dream-ap-mode"
}

remove_iptables_rules() {
  # Drop any PREROUTING rule tagged with our comment. Loop in case there
  # are multiple (e.g. a previous up didn't fully tear down).
  while iptables -t nat -C PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 80 \
      -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:80" -m comment --comment "dream-ap-mode" 2>/dev/null; do
    iptables -t nat -D PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 80 \
      -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:80" -m comment --comment "dream-ap-mode" || true
  done
  while iptables -t nat -C PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 443 \
      -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:443" -m comment --comment "dream-ap-mode" 2>/dev/null; do
    iptables -t nat -D PREROUTING -i "${DREAM_AP_INTERFACE}" -p tcp --dport 443 \
      -j DNAT --to-destination "${DREAM_AP_GATEWAY_IP}:443" -m comment --comment "dream-ap-mode" || true
  done
}

release_interface_from_nm() {
  # Tell NetworkManager to stop managing the AP interface. Otherwise it
  # fights hostapd over wlan0. nmcli returns non-zero if NM doesn't
  # currently manage the iface — that's fine.
  nmcli device set "${DREAM_AP_INTERFACE}" managed no 2>/dev/null || true
}

reclaim_interface_for_nm() {
  nmcli device set "${DREAM_AP_INTERFACE}" managed yes 2>/dev/null || true
}

bring_up_interface() {
  ip link set dev "${DREAM_AP_INTERFACE}" up
  ip addr flush dev "${DREAM_AP_INTERFACE}"
  ip addr add "${DREAM_AP_GATEWAY_IP}/${DREAM_AP_NETMASK}" dev "${DREAM_AP_INTERFACE}"
}

write_state() {
  local status="$1"
  cat > "${STATE_FILE}" <<HEREDOC
{
  "status": "${status}",
  "ssid": "${DREAM_AP_SSID}",
  "interface": "${DREAM_AP_INTERFACE}",
  "gateway_ip": "${DREAM_AP_GATEWAY_IP}",
  "since": "$(date -Iseconds)"
}
HEREDOC
  chmod 0644 "${STATE_FILE}"
}

cmd_up() {
  require_linux
  require_root
  require_binaries
  require_password
  interface_supports_ap

  mkdir -p "${RUN_DIR}"

  # Snapshot the original state so we can recover on teardown.
  log "bringing up AP on ${DREAM_AP_INTERFACE} as '${DREAM_AP_SSID}'"
  release_interface_from_nm
  bring_up_interface

  write_hostapd_conf
  write_dnsmasq_conf
  install_iptables_rules

  # Start daemons via systemd-run --scope so they're easy to track + kill
  # without each needing a wrapper unit. --no-block lets us continue.
  if ! pgrep -f "hostapd ${HOSTAPD_CONF}" >/dev/null; then
    hostapd -B -P "${HOSTAPD_PID}" "${HOSTAPD_CONF}" \
      || { err "hostapd failed to start — check journalctl"; cmd_down; return 1; }
  fi
  if ! pgrep -f "dnsmasq.*${DNSMASQ_CONF}" >/dev/null; then
    dnsmasq -C "${DNSMASQ_CONF}" --pid-file="${DNSMASQ_PID}" \
      || { err "dnsmasq failed to start — check ${RUN_DIR}/dnsmasq.log"; cmd_down; return 1; }
  fi

  write_state "active"
  log "AP up: SSID=${DREAM_AP_SSID} gateway=${DREAM_AP_GATEWAY_IP}"
  log "  any hostname resolves to ${DREAM_AP_GATEWAY_IP} (captive portal)"
  log "  HTTP/HTTPS on ${DREAM_AP_INTERFACE} redirected to the gateway"
}

cmd_down() {
  # Idempotent. Never errors out — best-effort cleanup so we don't leave
  # the system in a half-configured state.
  require_linux
  require_root

  log "tearing down AP on ${DREAM_AP_INTERFACE}"

  if [[ -f "${HOSTAPD_PID}" ]]; then
    kill "$(cat "${HOSTAPD_PID}")" 2>/dev/null || true
    rm -f "${HOSTAPD_PID}"
  fi
  pkill -f "hostapd ${HOSTAPD_CONF}" 2>/dev/null || true

  if [[ -f "${DNSMASQ_PID}" ]]; then
    kill "$(cat "${DNSMASQ_PID}")" 2>/dev/null || true
    rm -f "${DNSMASQ_PID}"
  fi
  pkill -f "dnsmasq.*${DNSMASQ_CONF}" 2>/dev/null || true

  remove_iptables_rules
  ip addr flush dev "${DREAM_AP_INTERFACE}" 2>/dev/null || true
  reclaim_interface_for_nm

  rm -f "${STATE_FILE}" "${HOSTAPD_CONF}" "${DNSMASQ_CONF}"
  log "AP down; ${DREAM_AP_INTERFACE} returned to NetworkManager"
}

cmd_status() {
  # No root required — purely read-only. Outputs JSON for the host-agent
  # to forward to the dashboard / wizard.
  if [[ -f "${STATE_FILE}" ]]; then
    cat "${STATE_FILE}"
  else
    printf '{"status":"inactive"}\n'
  fi
}

main() {
  case "${1:-status}" in
    up|start)       cmd_up ;;
    down|stop)      cmd_down ;;
    status)         cmd_status ;;
    -h|--help|help)
      cat <<HEREDOC
Usage: ap-mode.sh {up|down|status}

  up      Bring up the AP. DESTRUCTIVE — takes ${DREAM_AP_INTERFACE}
          off NetworkManager and applies iptables NAT rules.
  down    Tear down the AP and restore the prior state. Idempotent.
  status  Print JSON status (read-only).

Config is loaded from ${CONF_DIR}/ap-mode.conf if present.
See docs/AP-MODE.md for the full setting list.
HEREDOC
      ;;
    *)
      err "unknown command: $1 (try: up | down | status)"
      exit 2
      ;;
  esac
}

main "$@"
